[build]
  command = "npm run build"
  publish = "dist/"

[[redirects]]
  from = "/invite"
  to = "https://discord.com/oauth2/authorize?client_id=947365454828150854&permissions=478208&scope=bot%20applications.commands"

[[redirects]]
  from = "/support"
  to = "https://discord.gg/WUyghSWN22"
